[[rulesets]]
name = "macos"
includes = [
  "apps/chromium.toml",
  "macos/standard.toml",
  "macos/developer.toml",
  "macos/deep_clean.toml",
  "macos/protect.toml",
]

[[rulesets]]
name = "macos-minimal"
includes = [
  "apps/chromium.toml",
  "macos/standard.toml",
  "macos/protect.toml",
]
